# Site settings
title: Home
email: andres.fortier@gmail.com
description:
baseurl: ""
url: "http://andres-fortier.github.io/"
github_username: andres-fortier

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems: [jekyll-paginate]
